### Create a new Patient Entity
POST http://localhost:4004/api/patients
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc2Mzc4NzY4NCwiZXhwIjoxNzYzODIzNjg0fQ.zkrIIZDqpNVp9HxmRzHvJKQxbmhP6fJ-YjvW-vfIQ9M
Content-Type: application/json

{
  "name":"John Doe test28",
  "email": "testing28@example.com",
  "address": "123 street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"

}

###