### Create a new Patient Entity
POST http://localhost:4004/api/patients
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc2Mzc0MzUyOCwiZXhwIjoxNzYzNzc5NTI4fQ.i2KT2YLUQKfH_XK-vI67lpLpramCh8ej8NI2itpJ3pU
Content-Type: application/json

{
  "name":"John Doe test2",
  "email": "testing2@example.com",
  "address": "123 street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"

}

###